service: ${self:custom.appName}-app
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-s3-sync

custom:
  appName: wedding-invitation
  defaultStage: dev

  deletionPolicy:
    dev: Delete
    prod: Retain

  appDomain: 1nichi1shoku.jp
  frontDomain:
    dev: dev-wedding.${self:custom.appDomain}
    prod: wedding.${self:custom.appDomain}

  # serverless-s3-sync
  s3Sync:
    - bucketName: !Ref S3Bucket
      localDir: frontend/build

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  architecture: arm64
  memorySize: 128
  timeout: 6
  versionFunctions: false
  environment:
    NODE_OPTIONS: --enable-source-maps # ソースマップを有効にする

package:
  patterns:
    - '!frontend/**' # フロントエンドのコードはLambda関数に含めない

functions:
  hello:
    handler: backend/handler.hello
    events:
      - httpApi:
          path: /
          method: get

resources:
  - ${file(./resources/bucket.yml)}
  - ${file(./resources/oac.yml)}
  - ${file(./resources/distribution.yml)}
  - ${file(./resources/domain.yml)}
