service: ${self:custom.appName}-app
frameworkVersion: '3'

custom:
  appName: wedding-invitation
  defaultStage: dev

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  architecture: arm64
  memorySize: 128
  timeout: 6
  versionFunctions: false
  environment:
    NODE_OPTIONS: --enable-source-maps # ソースマップを有効にする

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  patterns:
    - '!frontend/**' # フロントエンドのコードはLambda関数に含めない

functions:
  hello:
    handler: backend/handler.hello
    events:
      - httpApi:
          path: /
          method: get
