Resources:
  CloudFrontARecord:
    Type: AWS::Route53::RecordSet
    DeletionPolicy: ${self:custom.deletionPolicy.${self:provider.stage}}
    Properties:
      HostedZoneName: ${env:APP_DOMAIN_NAME}.
      Name: ${self:custom.frontFQDN.${self:provider.stage}}
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName

  CloudFrontAAAARecord:
    Type: AWS::Route53::RecordSet
    DeletionPolicy: ${self:custom.deletionPolicy.${self:provider.stage}}
    Properties:
      HostedZoneName: ${env:APP_DOMAIN_NAME}.
      Name: ${self:custom.frontFQDN.${self:provider.stage}}
      Type: AAAA
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
